package redhat.medicare;

import org.joda.time.Years;
import org.joda.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicareApplicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer age;
   private java.util.Date dateOfBirth;
   private java.lang.Integer noOfYrsMedcarePaid;
   private java.lang.String anyotherInsurance;
   private java.lang.String liveInUS;
   private java.lang.String diabliltyOrSpecialCondition;
   private java.lang.String areYouUSCitizen;

   private java.lang.String eligibiliy;

   private java.lang.String reasonForNotEligible;

   public MedicareApplicant()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      Years years = Years.yearsBetween(new LocalDate(getDateOfBirth()), new LocalDate());
      this.age = years.getYears();

      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.util.Date getDateOfBirth()
   {
      return this.dateOfBirth;
   }

   public void setDateOfBirth(java.util.Date dateOfBirth)
   {
      this.dateOfBirth = dateOfBirth;
   }

   public java.lang.Integer getNoOfYrsMedcarePaid()
   {
      return this.noOfYrsMedcarePaid;
   }

   public void setNoOfYrsMedcarePaid(java.lang.Integer noOfYrsMedcarePaid)
   {
      this.noOfYrsMedcarePaid = noOfYrsMedcarePaid;
   }

   public java.lang.String getAnyotherInsurance()
   {
      return this.anyotherInsurance;
   }

   public void setAnyotherInsurance(java.lang.String anyotherInsurance)
   {
      this.anyotherInsurance = anyotherInsurance;
   }

   public java.lang.String getLiveInUS()
   {
      return this.liveInUS;
   }

   public void setLiveInUS(java.lang.String liveInUS)
   {
      this.liveInUS = liveInUS;
   }

   public java.lang.String getDiabliltyOrSpecialCondition()
   {
      return this.diabliltyOrSpecialCondition;
   }

   public void setDiabliltyOrSpecialCondition(
         java.lang.String diabliltyOrSpecialCondition)
   {
      this.diabliltyOrSpecialCondition = diabliltyOrSpecialCondition;
   }

   public java.lang.String getAreYouUSCitizen()
   {
      return this.areYouUSCitizen;
   }

   public void setAreYouUSCitizen(java.lang.String areYouUSCitizen)
   {
      this.areYouUSCitizen = areYouUSCitizen;
   }

   public java.lang.String getEligibiliy()
   {
      return this.eligibiliy;
   }

   public void setEligibiliy(java.lang.String eligibiliy)
   {
      this.eligibiliy = eligibiliy;
   }

   public java.lang.String getReasonForNotEligible()
   {
      return this.reasonForNotEligible;
   }

   public void setReasonForNotEligible(java.lang.String reasonForNotEligible)
   {
      this.reasonForNotEligible = reasonForNotEligible;
   }

   public MedicareApplicant(java.lang.String name, java.lang.Integer age,
         java.util.Date dateOfBirth, java.lang.Integer noOfYrsMedcarePaid,
         java.lang.String anyotherInsurance, java.lang.String liveInUS,
         java.lang.String diabliltyOrSpecialCondition,
         java.lang.String areYouUSCitizen, java.lang.String eligibiliy,
         java.lang.String reasonForNotEligible)
   {
      this.name = name;
      this.age = age;
      this.dateOfBirth = dateOfBirth;
      this.noOfYrsMedcarePaid = noOfYrsMedcarePaid;
      this.anyotherInsurance = anyotherInsurance;
      this.liveInUS = liveInUS;
      this.diabliltyOrSpecialCondition = diabliltyOrSpecialCondition;
      this.areYouUSCitizen = areYouUSCitizen;
      this.eligibiliy = eligibiliy;
      this.reasonForNotEligible = reasonForNotEligible;
   }

}