package redhat.workerscompensation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String claimId;
   private java.util.Date dateOfNotice;
   private java.util.Date informedDate;

   public Claim()
   {
   }

   public java.lang.String getClaimId()
   {
      return this.claimId;
   }

   public void setClaimId(java.lang.String claimId)
   {
      this.claimId = claimId;
   }

   public java.util.Date getDateOfNotice()
   {
      return this.dateOfNotice;
   }

   public void setDateOfNotice(java.util.Date dateOfNotice)
   {
      this.dateOfNotice = dateOfNotice;
   }

   public java.util.Date getInformedDate()
   {
      return this.informedDate;
   }

   public void setInformedDate(java.util.Date informedDate)
   {
      this.informedDate = informedDate;
   }

   public Claim(java.lang.String claimId, java.util.Date dateOfNotice,
         java.util.Date informedDate)
   {
      this.claimId = claimId;
      this.dateOfNotice = dateOfNotice;
      this.informedDate = informedDate;
   }

}