package redhat.workerscompensation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EmployeeInfo() {
    }

}