package redhat.workerscompensation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RecepientAction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String claimId;
   private java.lang.String actionItem;
   private java.lang.String displayName;
   private java.lang.String actionDetail;
   private java.lang.String recipientName;
   private java.lang.String recipientRole;
   private java.lang.String dueDays;

   public RecepientAction()
   {
   }

   public java.lang.String getClaimId()
   {
      return this.claimId;
   }

   public void setClaimId(java.lang.String claimId)
   {
      this.claimId = claimId;
   }

   public java.lang.String getActionItem()
   {
      return this.actionItem;
   }

   public void setActionItem(java.lang.String actionItem)
   {
      this.actionItem = actionItem;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public java.lang.String getActionDetail()
   {
      return this.actionDetail;
   }

   public void setActionDetail(java.lang.String actionDetail)
   {
      this.actionDetail = actionDetail;
   }

   public java.lang.String getRecipientName()
   {
      return this.recipientName;
   }

   public void setRecipientName(java.lang.String recipientName)
   {
      this.recipientName = recipientName;
   }

   public java.lang.String getRecipientRole()
   {
      return this.recipientRole;
   }

   public void setRecipientRole(java.lang.String recipientRole)
   {
      this.recipientRole = recipientRole;
   }

   public java.lang.String getDueDays()
   {
      return this.dueDays;
   }

   public void setDueDays(java.lang.String dueDays)
   {
      this.dueDays = dueDays;
   }

   public RecepientAction(java.lang.String claimId,
         java.lang.String actionItem, java.lang.String displayName,
         java.lang.String actionDetail, java.lang.String recipientName,
         java.lang.String recipientRole, java.lang.String dueDays)
   {
      this.claimId = claimId;
      this.actionItem = actionItem;
      this.displayName = displayName;
      this.actionDetail = actionDetail;
      this.recipientName = recipientName;
      this.recipientRole = recipientRole;
      this.dueDays = dueDays;
   }

}